### ISSUE TITLE
running exception error

### ISSUE THREAD

**Issue by skinjal55** [DigitalPhantom/PhantomWeatherAndroid#9]
weather.data open:ENOENT(No such file or directory found) toast msg in my project package

**Comment by ynunez** [comment]
@skinjal55 the exception you are seeing is because the fallback method to a reverse geocoding error is to load the data from the cache. However, in your case you cache was not existent and therefore you were getting that exception; the exception now is more clear. Hopefully that gives you a better idea of what the problem is.

**Comment by skinjal55** [comment]
thank u so much for your help...i solved that problem

On Tue, Mar 15, 2016 at 9:08 AM, Yoel Nunez notifications@github.com
wrote:

> Closed #9
> https://github.com/DigitalPhantom/PhantomWeatherAndroid/issues/9.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/DigitalPhantom/PhantomWeatherAndroid/issues/9#event-589712776

## 

_Thanks_
_Kinjal Shukla_
